apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo-app
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: python-demo-app
      role: web
  template:
    metadata:
      labels:
        app: python-demo-app
        role: web
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: "{{ .Values.imageCredentials.registry }}/{{ .Values.imageCredentials.username }}/{{ .Values.imageDetails.envprefix }}-{{ .Values.imageDetails.imagename }}:{{ .Values.imageDetails.tag }}"
          ports:
            - name: flask
              containerPort: 5000